#!/usr/bin/env bash
# Nginx runs as nginx user and must be listening on port 8080
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
